# Generated by Django 3.0.9 on 2020-09-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('code', models.CharField(max_length=100, verbose_name='Код')),
                ('name', models.CharField(max_length=400, verbose_name='Наименование')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
            ],
        ),
    ]
