# Generated by Django 3.0.9 on 2020-09-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paid_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='something',
            field=models.CharField(default='', max_length=50, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
