# Generated by Django 3.0.9 on 2020-09-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paid_services', '0002_service_something'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='something',
        ),
    ]
