# Generated by Django 3.0.9 on 2020-09-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='phones',
            field=models.TextField(verbose_name='Телефоны'),
        ),
    ]
