# Generated by Django 3.0.7 on 2020-09-18 07:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20200904_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='address',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='phones',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Телефоны'),
        ),
    ]
