# Generated by Django 3.0.7 on 2020-09-18 07:12

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20200918_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Контент'),
        ),
    ]
