# Generated by Django 3.0.9 on 2020-09-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_specialists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialists',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='date_sertif',
            field=models.CharField(max_length=100, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='date_vyz',
            field=models.CharField(max_length=100, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='degree',
            field=models.CharField(max_length=100, verbose_name='Степень'),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='division',
            field=models.CharField(max_length=300, verbose_name='Подразделение (Наименование)'),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='job',
            field=models.CharField(max_length=200, verbose_name='Штатная должность (Наименование)'),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='patronymic',
            field=models.CharField(max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='profession',
            field=models.CharField(max_length=200, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='sertif',
            field=models.CharField(max_length=100, verbose_name='Сертификат'),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='vyz',
            field=models.CharField(max_length=300, verbose_name='ВУЗ'),
        ),
    ]
